version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: MO-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - MO_data:/var/lib/postgresql/data/
      - ./resources/scripts/:/data/

  router_machine:
    restart: always
    image: osrm/osrm-backend
    container_name: MO-router-foot
    command: osrm-routed --algorithm mld /data/colombia-latest.osrm
    ports:
      - "5000:5000"
    volumes:
      - ./resources/data/foot_profile:/data/

  router_machine2:
    restart: always
    image: osrm/osrm-backend
    container_name: MO-router-car
    command: osrm-routed --algorithm mld /data/colombia-latest.osrm
    ports:
      - "5001:5000"
    volumes:
      - ./resources/data/car_profile:/data/

volumes:
  MO_data: